# Generated by Django 4.2.18 on 2025-01-20 19:26

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Баня из бруса 4х4', max_length=255, verbose_name='Введите название')),
                ('slug', models.SlugField(help_text='Например: bany-4x4', max_length=255, unique=True, verbose_name='URL')),
                ('description_primary', ckeditor.fields.RichTextField(help_text='Введите описание', verbose_name='Что входит в стоимость?')),
                ('description_secondary', ckeditor.fields.RichTextField(help_text='Введите описание', verbose_name='Дополнительные работы')),
                ('width', models.IntegerField(help_text='Введите ширину в метрах', verbose_name='Ширина')),
                ('height', models.IntegerField(help_text='Введите высоту в метрах', verbose_name='Высота')),
                ('total_area', models.IntegerField(help_text='Введите общую площадь в метрах', verbose_name='Общая площадь')),
                ('price', models.IntegerField(help_text='Введите цену в рублях', verbose_name='Цена')),
                ('image', models.ImageField(upload_to='images/ready_baths/', verbose_name='Основное изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
            ],
            options={
                'verbose_name': 'Баня',
                'verbose_name_plural': 'Бани',
            },
        ),
        migrations.CreateModel(
            name='BathLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Терраса', max_length=255, verbose_name='название помещения')),
                ('area', models.DecimalField(decimal_places=2, help_text='Введите площадь в метрах', max_digits=5, verbose_name='Площадь')),
                ('bath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ready_baths.bath', verbose_name='Баня')),
            ],
            options={
                'verbose_name': 'Планировка',
                'verbose_name_plural': 'Планировки',
            },
        ),
        migrations.CreateModel(
            name='BathGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/baths/', verbose_name='Изображение')),
                ('bath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ready_baths.bath', verbose_name='Баня')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение',
                'verbose_name_plural': 'Дополнительные изображения',
            },
        ),
    ]
