# Generated by Django 4.2.18 on 2025-01-20 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor_baths', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bath',
            options={'verbose_name': 'Баня', 'verbose_name_plural': 'Бани'},
        ),
    ]
