# Generated by Django 4.2.18 on 2025-01-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Например: +78007776655', max_length=22, verbose_name='Номер телефона')),
                ('phone_format', models.CharField(help_text='Например: +7(800)777-66-55', max_length=255, verbose_name='Формат номера телефона')),
                ('email', models.EmailField(help_text='Например: info@company.ru', max_length=254, verbose_name='Адрес эл.почты')),
                ('social_vk', models.URLField(blank=True, help_text='Вставьте url-ссылку сообщества вконтакте', null=True, verbose_name='Вконтакте')),
                ('social_tg', models.URLField(blank=True, help_text='Вставьте url-ссылку сообщества телеграм', null=True, verbose_name='Телеграм')),
                ('social_youtube', models.URLField(blank=True, help_text='Вставьте url-ссылку сообщества Youtube', null=True, verbose_name='YouTube')),
                ('address', models.CharField(help_text='Например: г. Москва, ул. Пушкина, д. 1', max_length=255, verbose_name='Адрес')),
                ('working_hours', models.CharField(help_text='Например: Ежедневно с 9.00 до 21.00', max_length=255, verbose_name='График работы')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
